apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w3gl85o0n-python
  janus-idp.io/tekton: w3gl85o0n-python
  backstage.io/kubernetes-id: w3gl85o0n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w3gl85o0n-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
